version: '3.1'

services:

  db:
    image: mysql
    network_mode: "host"
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
    volumes:
    - db:/var/lib/mysql

volumes:
  db:
